### ISSUE TITLE
Anki: Add Local Font

### ISSUE THREAD

**Issue by MarvNC** [MarvNC/kanjidego-yomitan-anki#11]
https://github.com/cjkvi/HanaMinAFDKO
https://learn.microsoft.com/en-us/typography/font-list/simsun

Font loading mitigation: https://discord.com/channels/617136488840429598/1041466793094557879/1081035873430290502

```css
/* a hack to no longer depend on the installed font (to speed up card load times) */
.android .card {
  font-family: "Noto Sans", "Noto Sans CJK JP", "Open Sans", "Droid Sans", "Ubuntu", "Roboto", "Source Han Sans JP", "IPAPGothic", "VL PGothic", "Koruri", sans-serif;
}
.android .card-description {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .card-description-right {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .info-circle-text {
  font-family: "Noto Sans", "Noto Sans CJK JP", "Open Sans", "Droid Sans", "Ubuntu", "Roboto", "Source Han Sans JP", "IPAPGothic", "VL PGothic", "Koruri", sans-serif;
}
.android .expression {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .expression--single {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .dh-left__reading {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .hover-tooltip-wrapper {
  font-family: "Noto Sans", "Noto Sans CJK JP", "Open Sans", "Droid Sans", "Ubuntu", "Roboto", "Source Han Sans JP", "IPAPGothic", "VL PGothic", "Koruri", sans-serif;
}
.android .full-sentence {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
.android .frequencies {
  font-family: "Noto Serif", "Noto Serif CJK JP", "Droid Serif", "Roboto Slab", "IPAPMincho", "HanaMinA", "HanaMinB", serif;
}
```
